distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
wrapperUrl=https://repo1.maven.org/maven2/io/takari/maven-wrapper/0.6.5/maven-wrapper.jar
distributionSha256Sum=d39e8c635ed2bb2ba3572c04ef5c4f6d8fbc5a6fde36b6b4d3ed1419f23f3017
wrapperChecksum=ad0f40a94e4458d10c957651d2a6e4ac5f64d9ac3e8ad4b75be235186d5900d9